import { periodTotals } from "./calculations";
import { FixedExpensePeriodOverride, FixedMonthlyExpense, Transaction } from "./types";

/**
 * A fixed monthly expense has no stored "paid/upcoming" status anywhere —
 * it's derived by checking whether a transaction generated for it (see
 * Transaction.fixedExpenseId) falls within the given period's date range.
 * Always recomputed from the current financial-period-start-day setting,
 * never cached against a stale period boundary — this is what keeps
 * changing that setting safe (see domain/financialPeriod.ts) and what
 * makes "mark as unpaid" just "delete this transaction", with nothing else
 * to desync.
 */
export function findPaidTransaction(
  transactions: readonly Transaction[],
  fixedExpenseId: string,
  fromDate: string,
  toDate: string,
): Transaction | undefined {
  return transactions.find((t) => t.fixedExpenseId === fixedExpenseId && t.date >= fromDate && t.date <= toDate);
}

export interface FixedExpenseForPeriod {
  fixedExpense: FixedMonthlyExpense;
  /** The override amount for this period if one was set, otherwise the fixed expense's own default. */
  expectedAmountMinor: number;
  isPaid: boolean;
  paidTransaction?: Transaction;
}

/** Combines each fixed expense with its expected amount and derived paid/upcoming status for one period. */
export function fixedExpensesForPeriod(
  fixedExpenses: readonly FixedMonthlyExpense[],
  overrides: readonly FixedExpensePeriodOverride[],
  transactions: readonly Transaction[],
  fromDate: string,
  toDate: string,
): FixedExpenseForPeriod[] {
  const overrideByExpenseId = new Map(overrides.map((o) => [o.fixedExpenseId, o]));
  return fixedExpenses.map((fixedExpense) => {
    const expectedAmountMinor = overrideByExpenseId.get(fixedExpense.id)?.amountMinor ?? fixedExpense.defaultAmountMinor;
    const paidTransaction = findPaidTransaction(transactions, fixedExpense.id, fromDate, toDate);
    return { fixedExpense, expectedAmountMinor, isPaid: Boolean(paidTransaction), paidTransaction };
  });
}

export interface ForecastSummary {
  incomeMinor: number;
  /** All expense transactions in the period — including ones generated by marking a fixed expense paid, so nothing is double-counted against upcomingFixedMinor below. */
  paidExpenseMinor: number;
  /** Sum of expectedAmountMinor across fixed expenses not yet paid for this period. */
  upcomingFixedMinor: number;
  /** Actual: income minus actual paid expenses so far. */
  currentBalanceMinor: number;
  /** Forecast: currentBalance minus what's still expected to come due this period. */
  expectedRemainingMinor: number;
}

export function forecastSummary(
  transactions: readonly Transaction[],
  statuses: readonly FixedExpenseForPeriod[],
  fromDate: string,
  toDate: string,
): ForecastSummary {
  const totals = periodTotals(transactions, fromDate, toDate);
  const upcomingFixedMinor = statuses.filter((s) => !s.isPaid).reduce((sum, s) => sum + s.expectedAmountMinor, 0);
  const currentBalanceMinor = totals.incomeMinor - totals.expenseMinor;

  return {
    incomeMinor: totals.incomeMinor,
    paidExpenseMinor: totals.expenseMinor,
    upcomingFixedMinor,
    currentBalanceMinor,
    expectedRemainingMinor: currentBalanceMinor - upcomingFixedMinor,
  };
}
