export type TransactionType = "income" | "expense";

export interface Transaction {
  id: string;
  type: TransactionType;
  /** Integer count of the smallest currency unit (øre for NOK) — never a float. See domain/money.ts. */
  amountMinor: number;
  /** "YYYY-MM-DD" — the user's intended local calendar date. No time component, no timezone. */
  date: string;
  categoryId: string;
  note?: string;
  /**
   * Set only on a transaction auto-generated by "mark as paid" for a fixed
   * monthly expense (see FixedMonthlyExpense below) — links it back to that
   * expense. A fixed expense's paid/upcoming status for a given financial
   * period is *derived* by checking whether such a transaction's date falls
   * within that period's date range (recomputed from the current start-day
   * setting, never cached) — there is no separate status field anywhere,
   * so deleting this transaction is exactly how "mark as unpaid" works.
   * UpdateTransactionInput never exposes this as user-editable — the normal
   * edit sheet has no control for it, so an edit can't accidentally clear
   * the link.
   */
  fixedExpenseId?: string;
  /** ISO 8601 timestamp — bookkeeping metadata, not calendar-date semantics. */
  createdAt: string;
  updatedAt: string;
}

export interface Category {
  /** Stable slug for a default category (e.g. "groceries"), a uuid for a custom one. */
  id: string;
  type: TransactionType;
  /** i18n key for a default category's label; null means custom (use `name` instead). */
  labelKey: string | null;
  /** User-entered literal name for a custom category; null for defaults. */
  name: string | null;
  createdAt: string;
}

export interface TransactionFilter {
  /** "YYYY-MM-DD", inclusive. Period boundaries are computed by domain/financialPeriod.ts — this filter itself is period-agnostic. */
  fromDate?: string;
  /** "YYYY-MM-DD", inclusive. */
  toDate?: string;
  categoryId?: string;
  type?: TransactionType;
}

export interface FinanceSettings {
  /** Day of month (1-31) a financial period starts on — see domain/financialPeriod.ts. Defaults to 1 (plain calendar months). */
  financialPeriodStartDay: number;
}

/** An inclusive "YYYY-MM-DD" date range — the shape domain/financialPeriod.ts's periodDateRange() returns. */
export interface DateRange {
  fromDate: string;
  toDate: string;
}

export interface FixedMonthlyExpense {
  id: string;
  name: string;
  categoryId: string;
  /** Integer minor units — the amount expected for a period unless overridden (see FixedExpensePeriodOverride). */
  defaultAmountMinor: number;
  /** Day of month (1-31) this is typically due, purely informational (not clamped/validated against period boundaries). */
  dueDay?: number;
  /** Archived (false) fixed expenses are excluded from getFixedExpenses() by default but kept forever — past linked transactions and overrides must stay intact. Never hard-deleted. */
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

/** A per-period override of a fixed expense's expected amount — keyed by the opaque "YYYY-MM" period id it was set for. */
export interface FixedExpensePeriodOverride {
  fixedExpenseId: string;
  periodId: string;
  amountMinor: number;
}

export type CreateTransactionInput = Omit<Transaction, "id" | "createdAt" | "updatedAt">;
export type UpdateTransactionInput = Partial<Omit<Transaction, "id" | "createdAt" | "updatedAt">>;

export type CreateCategoryInput = Pick<Category, "type" | "name">;
export type UpdateCategoryInput = Pick<Category, "name">;

export type CreateFixedExpenseInput = Omit<FixedMonthlyExpense, "id" | "isActive" | "createdAt" | "updatedAt">;
export type UpdateFixedExpenseInput = Partial<Omit<FixedMonthlyExpense, "id" | "isActive" | "createdAt" | "updatedAt">>;

/** Thrown by deleteCategory when a transaction still references it — see the repository interface. */
export class CategoryInUseError extends Error {
  constructor(public readonly categoryId: string, public readonly transactionCount: number) {
    super(`Category "${categoryId}" is referenced by ${transactionCount} transaction(s)`);
    this.name = "CategoryInUseError";
  }
}
