// <auto-generated />
using System;
using IAmFara.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IAmFara.Web.Data.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260916133006_AddAnalyticsTables")]
    partial class AddAnalyticsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IAmFara.Web.Data.Entities.AnalyticsDailyCountryBreakdown", b =>
                {
                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<int>("PageViewCount")
                        .HasColumnType("int");

                    b.Property<int>("UniqueVisitorCount")
                        .HasColumnType("int");

                    b.HasKey("LocalDate", "CountryCode");

                    b.ToTable("DailyCountryBreakdowns");
                });

            modelBuilder.Entity("IAmFara.Web.Data.Entities.AnalyticsDailyPageBreakdown", b =>
                {
                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<string>("NormalizedPath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PageViewCount")
                        .HasColumnType("int");

                    b.HasKey("LocalDate", "NormalizedPath");

                    b.ToTable("DailyPageBreakdowns");
                });

            modelBuilder.Entity("IAmFara.Web.Data.Entities.AnalyticsDailySummary", b =>
                {
                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<int>("PageViewCount")
                        .HasColumnType("int");

                    b.Property<int>("UniqueVisitorCount")
                        .HasColumnType("int");

                    b.HasKey("LocalDate");

                    b.ToTable("DailySummaries");
                });

            modelBuilder.Entity("IAmFara.Web.Data.Entities.AnalyticsReportRun", b =>
                {
                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResendMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ReportDate");

                    b.ToTable("ReportRuns");
                });

            modelBuilder.Entity("IAmFara.Web.Data.Entities.AnalyticsVisit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("DailyVisitorKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("NormalizedPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("OccurredAtUtc", "CountryCode");

                    b.HasIndex("OccurredAtUtc", "DailyVisitorKey");

                    b.HasIndex("OccurredAtUtc", "NormalizedPath");

                    b.ToTable("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
