// <auto-generated />
using System;
using IAmFara.Data.SqlServer.Finance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IAmFara.Data.SqlServer.Migrations.Finance
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260919093806_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LabelKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Categories", "finance");
                });

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.FinancialPeriodSettings", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FinancialPeriodStartDay")
                        .HasColumnType("int");

                    b.HasKey("HouseholdId");

                    b.ToTable("FinancialPeriodSettings", "finance");
                });

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.FixedExpensePeriodOverride", b =>
                {
                    b.Property<Guid>("FixedExpenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PeriodId")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.HasKey("FixedExpenseId", "PeriodId");

                    b.ToTable("FixedExpensePeriodOverrides", "finance");
                });

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.FixedMonthlyExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("DefaultAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<int?>("DueDay")
                        .HasColumnType("int");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("FixedMonthlyExpenses", "finance");
                });

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Households", "finance");
                });

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.HouseholdInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdentityInvitationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varbinary(900)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("HouseholdInvitations", "finance");
                });

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.HouseholdMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("UserId", "HouseholdId")
                        .IsUnique();

                    b.ToTable("HouseholdMemberships", "finance");
                });

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid?>("FixedExpenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FixedExpenseId");

                    b.HasIndex("HouseholdId", "Date");

                    b.ToTable("Transactions", "finance");
                });

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.Category", b =>
                {
                    b.HasOne("IAmFara.Data.Abstractions.Finance.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.FinancialPeriodSettings", b =>
                {
                    b.HasOne("IAmFara.Data.Abstractions.Finance.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.FixedExpensePeriodOverride", b =>
                {
                    b.HasOne("IAmFara.Data.Abstractions.Finance.FixedMonthlyExpense", null)
                        .WithMany()
                        .HasForeignKey("FixedExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.FixedMonthlyExpense", b =>
                {
                    b.HasOne("IAmFara.Data.Abstractions.Finance.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAmFara.Data.Abstractions.Finance.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.HouseholdInvitation", b =>
                {
                    b.HasOne("IAmFara.Data.Abstractions.Finance.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.HouseholdMembership", b =>
                {
                    b.HasOne("IAmFara.Data.Abstractions.Finance.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IAmFara.Data.Abstractions.Finance.Transaction", b =>
                {
                    b.HasOne("IAmFara.Data.Abstractions.Finance.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IAmFara.Data.Abstractions.Finance.FixedMonthlyExpense", null)
                        .WithMany()
                        .HasForeignKey("FixedExpenseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IAmFara.Data.Abstractions.Finance.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
