namespace IAmFara.Data.Abstractions.Finance;

public class Transaction
{
    public Guid Id { get; set; }
    public Guid HouseholdId { get; set; }
    public TransactionType Type { get; set; }
    /// <summary>Integer count of the smallest currency unit — never a float.</summary>
    public long AmountMinor { get; set; }
    /// <summary>The user's intended local calendar date — no time component, no timezone.</summary>
    public DateOnly Date { get; set; }
    public Guid CategoryId { get; set; }
    public string? Note { get; set; }
    /// <summary>Set only on a transaction auto-generated by "mark as paid" for a fixed monthly expense. CreatedByUserId carries no database FK — see HouseholdMembership.</summary>
    public Guid? FixedExpenseId { get; set; }
    public Guid CreatedByUserId { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset UpdatedAt { get; set; }
}
