# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: false  # 💣 turn off cache completely

      - name: Clean all npm config
        run: |
          rm -f ~/.npmrc
          rm -f .npmrc
          rm -f src/frontend/.npmrc
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          npm config set registry https://registry.npmjs.org/
          npm config delete '//registry.npmjs.org/:_authToken'

      - name: Force clean install without auth
        working-directory: src/frontend
        env:
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
          NPM_CONFIG_AUTH: ""
        run: |
          rm -rf node_modules package-lock.json
          npm install --no-audit --no-fund
          npm run build

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Build and Publish Backend
        working-directory: src/backend
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: iamfara.com
          username: ${{ secrets.FTP_User_Name }}
          password: ${{ secrets.FTP_Password }}
          local-dir: ./src/backend/publish/
