# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Reset npm config
        run: |
            npm config delete '//registry.npmjs.org/:_authToken'
            npm config set registry https://registry.npmjs.org/

      - name: Build and Copy Frontend
        working-directory: src/frontend
        run: |
          npm install
          npm run build

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Build and Publish Backend
        working-directory: src/Backend
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: iamfara.com
          username: ${{ secrets.FTP_User_Name }}
          password: ${{ secrets.FTP_Password }}
          local-dir: ./src/Backend/publish/
